version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/go-app"
    schedule:
      interval: weekly
    labels:
      - "🤖 Dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
