FROM golang:1.22.4-alpine AS builder
WORKDIR /usr/src/app/
COPY . .
WORKDIR /usr/src/app/worker
RUN go build -o /go/bin/

FROM alpine:latest AS runner
WORKDIR /usr/src/app/
COPY --from=builder /go/bin/ .
ENTRYPOINT [ "./worker" ]