apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: localstack
  name: localstack
spec:
  ports:
    - name: "4566"
      port: 4566
      targetPort: 4566
    - name: 4566-tcp
      port: 4566
      targetPort: 4566
  selector:
    io.kompose.service: localstack
