// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: simple.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DeviceConfiguratorClient is the client API for DeviceConfigurator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceConfiguratorClient interface {
	UpdateDeviceConfig(ctx context.Context, in *DeviceConfig, opts ...grpc.CallOption) (*ConfigResult, error)
}

type deviceConfiguratorClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceConfiguratorClient(cc grpc.ClientConnInterface) DeviceConfiguratorClient {
	return &deviceConfiguratorClient{cc}
}

func (c *deviceConfiguratorClient) UpdateDeviceConfig(ctx context.Context, in *DeviceConfig, opts ...grpc.CallOption) (*ConfigResult, error) {
	out := new(ConfigResult)
	err := c.cc.Invoke(ctx, "/protos.DeviceConfigurator/UpdateDeviceConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceConfiguratorServer is the server API for DeviceConfigurator service.
// All implementations must embed UnimplementedDeviceConfiguratorServer
// for forward compatibility
type DeviceConfiguratorServer interface {
	UpdateDeviceConfig(context.Context, *DeviceConfig) (*ConfigResult, error)
	mustEmbedUnimplementedDeviceConfiguratorServer()
}

// UnimplementedDeviceConfiguratorServer must be embedded to have forward compatible implementations.
type UnimplementedDeviceConfiguratorServer struct {
}

func (UnimplementedDeviceConfiguratorServer) UpdateDeviceConfig(context.Context, *DeviceConfig) (*ConfigResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDeviceConfig not implemented")
}
func (UnimplementedDeviceConfiguratorServer) mustEmbedUnimplementedDeviceConfiguratorServer() {}

// UnsafeDeviceConfiguratorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceConfiguratorServer will
// result in compilation errors.
type UnsafeDeviceConfiguratorServer interface {
	mustEmbedUnimplementedDeviceConfiguratorServer()
}

func RegisterDeviceConfiguratorServer(s grpc.ServiceRegistrar, srv DeviceConfiguratorServer) {
	s.RegisterService(&DeviceConfigurator_ServiceDesc, srv)
}

func _DeviceConfigurator_UpdateDeviceConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceConfig)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceConfiguratorServer).UpdateDeviceConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.DeviceConfigurator/UpdateDeviceConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceConfiguratorServer).UpdateDeviceConfig(ctx, req.(*DeviceConfig))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceConfigurator_ServiceDesc is the grpc.ServiceDesc for DeviceConfigurator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceConfigurator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.DeviceConfigurator",
	HandlerType: (*DeviceConfiguratorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateDeviceConfig",
			Handler:    _DeviceConfigurator_UpdateDeviceConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simple.proto",
}
